# Generated by rust2rpm 11
%bcond_without check
%global debug_package %{nil}

%global crate backtrace-sys

Name:           rust-%{crate}
Version:        0.1.32
Release:        2%{?dist}
Summary:        Bindings to the libbacktrace gcc library

# Upstream license specification: MIT/Apache-2.0
# src/libbacktrace is BSD
# https://github.com/rust-lang/backtrace-rs/pull/269
License:        (MIT or ASL 2.0) and BSD
URL:            https://crates.io/crates/backtrace-sys
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Bindings to the libbacktrace gcc library.}

%description %{_description}

%package        devel
Summary:        %{summary}
# Some snapshot from 2018
Provides:       bundled(libbacktrace)
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.32-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Dec 16 2019 Josh Stone <jistone@redhat.com> - 0.1.32-1
- Update to 0.1.32

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.28-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jun 22 09:48:15 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.28-3
- Regenerate

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.28-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Mon Jan 07 2019 Josh Stone <jistone@redhat.com> - 0.1.28-1
- Update to 0.1.28

* Thu Dec 20 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.24-3
- Run tests in infrastructure

* Fri Nov 02 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.24-2
- Adapt to new packaging

* Wed Aug 15 2018 Josh Stone <jistone@redhat.com> - 0.1.24-1
- Update to 0.1.24

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.23-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Tue May 29 2018 Josh Stone <jistone@redhat.com> - 0.1.23-1
- Update to 0.1.23

* Wed May 23 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.19-1
- Update to 0.1.19

* Wed May 23 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.17-1
- Update to 0.1.17

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.16-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.16-2
- Rebuild for rust-packaging v5

* Fri Jun 16 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.11-1
- Initial package
